<Project Sdk="Microsoft.NET.Sdk.Web">
    <Import Project="..\..\..\common.props" />

    <PropertyGroup>
        <OutputType>exe</OutputType>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
        <PublishTrimmed>false</PublishTrimmed>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <!-- プロジェクト参照 -->
    <ItemGroup>
        <ProjectReference Include="..\..\KyoshinEewViewer.Core\KyoshinEewViewer.Core.csproj" />
    </ItemGroup>

    <!-- パッケージ参照 -->
    <ItemGroup>
        <!-- Kafka -->
        <PackageReference Include="Confluent.Kafka" Version="2.8.0" />
        <!-- OpenTelemetry -->
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.11.2" />
    </ItemGroup>
</Project>
