[package]
name = "kevi-launcher"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "kevi-launcher"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
strip = true

[dependencies]
netcorehost = { version = "0.20", default-features = false, features = ["nethost-download", "net10_0"] }
png = { version = "0.18", default-features = false }
sha2 = { version = "0.10", default-features = false }
zip = { version = "5", default-features = false, features = ["deflate", "zstd"] }

[build-dependencies]
sha2 = { version = "0.10", default-features = false }
walkdir = "2"
zip = { version = "5", default-features = false, features = ["deflate", "zstd"] }
winresource = "0.1"
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_GdiPlus",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Performance",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
