<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<IsTrimmable>true</IsTrimmable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="3.1.8" />
		<PackageReference Include="StringLiteralGenerator" Version="2.0.0" />
		<PackageReference Include="U8XmlParser" Version="1.6.1" />
	</ItemGroup>
</Project>
