//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyoshinEewViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KyoshinEewViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   震度アイコンテーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsIntensityTheme {
            get {
                return ResourceManager.GetString("SettingsIntensityTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウテーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindowTheme {
            get {
                return ResourceManager.GetString("SettingsWindowTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardBefore {
            get {
                return ResourceManager.GetString("SetupWizardBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これで一通りの初期設定は完了です。
        ///
        ///右下の『起動』ボタンからアプリの起動が可能です。  
        ///設定ウィンドウは右上の歯車アイコンのボタンを押すことで開くことができます。  
        ///このウィザードで設定した内容はごく一部で、かなり設定できる項目が多いので、自分好みにカスタマイズしてみてください。
        ///
        ///KyoshinEewViewer for ingen はまだまだ開発中です。  
        ///不具合や違和感がある場所がありましたら気軽に作者までお問い合わせください。  
        ///問い合わせ先は設定ウィンドウの一番下のタブに記載があります。
        ///
        ///---
        ///
        ///## ご利用にあたってのTips
        ///### 音声を鳴らしたい
        ///
        ///設定ウィンドウの『音声』タブより可能です。  
        ///`{int}: 最大震度` のような表記がある項目に対しては最大震度などに応じて再生するファイル名を変更することができます。  
        ///`C:\Sound\{int}.wav` のように指定すると震度5弱のときには `C:\Sound\5+.wav` が再生されます。
        ///
        ///### 録画などで利用したい
        ///
        ///配信や録画で使用する場合、上のタブ部分が邪魔にな [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardEpiloguePageContent {
            get {
                return ResourceManager.GetString("SetupWizardEpiloguePageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さいごに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardEpiloguePageTitle {
            get {
                return ResourceManager.GetString("SetupWizardEpiloguePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardNext {
            get {
                return ResourceManager.GetString("SetupWizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardRun {
            get {
                return ResourceManager.GetString("SetupWizardRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地図(日本国内) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewMapJapan {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewMapJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地図(海外) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewMapOther {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewMapOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通常ウィジェット中身 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewNormalDockContent {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewNormalDockContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通常ウィジェット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewNormalDockTitle {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewNormalDockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewTitle {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   緊急ウィジェット中身 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewWarningDockContent {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewWarningDockContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   緊急ウィジェット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePagePreviewWarningDockTitle {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePagePreviewWarningDockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSelectThemePageTitle {
            get {
                return ResourceManager.GetString("SetupWizardSelectThemePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキップして起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardSkipAndRun {
            get {
                return ResourceManager.GetString("SetupWizardSkipAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションは
        ///
        ///- 強震モニタによるリアルタイム震度
        ///- 強震モニタ･SignalNowProfessional経由での緊急地震速報
        ///- 気象庁HP･DM-D.S.S.経由による地震情報
        ///
        ///などの受信･表示などを行うことができます。
        ///
        ///アプリケーションの利用を始める前に、利用したい機能･外観に合わせてアプリケーションをカスタマイズしてみましょう。
        ///
        ///これらの設定はこのウィザードが終了しても設定ウィンドウから再度変更することが可能です。  
        ///お急ぎの方は『スキップして起動』ボタンをご利用ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardWelcomePageFunctionDetail {
            get {
                return ResourceManager.GetString("SetupWizardWelcomePageFunctionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KyoshinEewViewer for ingen へようこそ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardWelcomePageTitle {
            get {
                return ResourceManager.GetString("SetupWizardWelcomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KyoshinEewViewer for ingen へよこそう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWizardWelcomePageTitleAlt {
            get {
                return ResourceManager.GetString("SetupWizardWelcomePageTitleAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] ShindoObsPoints {
            get {
                object obj = ResourceManager.GetObject("ShindoObsPoints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   ## [Project DM-D.S.S.](https://dmdata.jp/)とは
        ///
        ///WebSocketなどを利用してリアルタイムに地震情報などの配信を行うサービスです。(有料)  
        ///KyoshinEewViewer for ingen ではデフォルトの状態で[防災情報XML(PULL型)](http://xml.kishou.go.jp/xmlpull.html)を使用して地震情報の受信を行いますが、この方法では発表から受信までに**1～3分程度**ラグが発生します。  
        ///そこを DM-D.S.S. を使用することで**数秒程度**に抑えることができ、テレビや企業が提供しているアプリと同等もしくはそれ以上の速度で情報の受信が可能になります。
        ///
        ///## 価格
        ///
        ///|区分|価格(月最大)|価格(日割り)|
        ///|---|---|
        ///|緊急地震（予報）|1650円/月|75円/日|
        ///|緊急地震（警報）|440円/月|20円/日|
        ///|地震・津波関連|550円/月|25円/日|
        ///
        ///(2022年7月時点/このソフトで使用可能なもののみ)
        ///
        ///ご利用の際はアカウント登録･契約の上アプリ起動後、設 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StetupWizardDmdataPromotionContent {
            get {
                return ResourceManager.GetString("StetupWizardDmdataPromotionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project DM-D.S.S. のご紹介 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StetupWizardDmdataPromotionTitle {
            get {
                return ResourceManager.GetString("StetupWizardDmdataPromotionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セットアップウィザード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StetupWizardWindowTitle {
            get {
                return ResourceManager.GetString("StetupWizardWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] tjma2001 {
            get {
                object obj = ResourceManager.GetObject("tjma2001", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
