<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\..\common.props" />

	<PropertyGroup>
		<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
		<WasmMainJSPath>AppBundle\main.js</WasmMainJSPath>
		<OutputType>Exe</OutputType>

        <DefineConstants>USE_SKIA_PATH</DefineConstants>
        <PublishReadyToRun>false</PublishReadyToRun>
        <RunAOTCompilation Condition="'$(Configuration)' == 'Release'">true</RunAOTCompilation>
        <WasmBuildNative Condition="'$(Configuration)' == 'Release'">true</WasmBuildNative>
        <PublishTrimmed Condition="'$(Configuration)' == 'Release'">true</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<WasmExtraFilesToDeploy Include="AppBundle\**" />
		<WasmExtraFilesToDeploy Include="AppBundle\.nojekyll" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CustomRenderItemTest\CustomRenderItemTest.csproj" />
	</ItemGroup>
</Project>
