name: release PiDASPlusGraph

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "0.1.2"
jobs:
  publish:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu]
        arch: [x64, arm64]
    env:
      RELEASE_PREFIX: PiDASPlusGraph
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: 'recursive'
    - uses: FranzDiebold/github-env-vars-action@e8118971bd6b60524ae66a2d870bc83088e3a3c9 # v2.9.0

    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: 10.0.x

    - name: Build
      run: >
        dotnet publish src/Sandboxes/PiDASPlusGraph/PiDASPlusGraph.csproj
        -c Release
        -r ${{ fromJson('{ "windows": "win", "ubuntu": "linux" }')[matrix.os] }}-${{ matrix.arch }}
        -o tmp
        -p:PublishSingleFile=true
        --self-contained true
      env:
        APP_VERSION: ${{ github.event.inputs.version }}
        BUILD_NUMBER: ${{ env.CI_RUN_NUMBER }}

    - name: Add permission
      if: matrix.os != 'windows'
      run: |
        chmod +x tmp/PiDASPlusGraph

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ env.RELEASE_PREFIX }}-${{ github.event.inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
        path: tmp/*
